name: Build & Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      
      - name: Install deps
        run: pnpm install
          
      - run: pnpm test:panel
