name: Publish Preview Package
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Build App
        run: |
          pnpm build:panel
    

      - name: Publish with pnpm
        run: |
            cd packages/trpc-ui
            pnpm install
            pnpm pkg-pr-new publish --pnpm --packageManager=pnpm