name: Publish Preview Package
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Build App
        run: |
          pnpm build:panel
    

      - name: Publish with pnpm
        run: |
            cd packages/trpc-ui
            pnpm install
            pnpm pkg-pr-new publish --pnpm --packageManager=pnpm